<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJxxshjm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJxxshjm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJxxshjm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJxxshjm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJxxshjm\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jxxshjm',
    'container.build_id' => 'fd09e187',
    'container.build_time' => 1597345412,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJxxshjm');
